// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using thefirey33.catpetterzBackend.Types.Database;

#nullable disable

namespace thefirey33.catpetterzBackend.Migrations
{
    [DbContext(typeof(CatpetterzDbContext))]
    partial class CatpetterzDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("thefirey33.catpetterzbackend.Types.Database.CatDbType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Health")
                        .HasColumnType("double precision")
                        .HasJsonPropertyName("health");

                    b.Property<byte>("Hunger")
                        .HasColumnType("smallint")
                        .HasJsonPropertyName("hunger");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasJsonPropertyName("name");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasJsonPropertyName("owner");

                    b.Property<bool>("TheCatWentOnSomeAdventures")
                        .HasColumnType("boolean")
                        .HasJsonPropertyName("the_cat_went_on_some_adventures");

                    b.Property<byte>("Thirst")
                        .HasColumnType("smallint")
                        .HasJsonPropertyName("thirst");

                    b.HasKey("Id");

                    b.ToTable("Cats");
                });
#pragma warning restore 612, 618
        }
    }
}
