// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using thefirey33_backend.Types.Database.Context;

#nullable disable

namespace thefirey33_backend.Migrations.NikoDexRecovery
{
    [DbContext(typeof(NikoDexRecoveryContext))]
    [Migration("20260724130255_InitialCreateNikoDexRecovery")]
    partial class InitialCreateNikoDexRecovery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("thefirey33_backend.Types.Database.NikoDexRecoveryDbType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasJsonPropertyName("filepath");

                    b.HasKey("Id");

                    b.ToTable("NikoDexRecovery");
                });
#pragma warning restore 612, 618
        }
    }
}
