// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using thefirey33_backend.Types.Database.Context;

#nullable disable

namespace thefirey33_backend.Migrations.Question
{
    [DbContext(typeof(QuestionContext))]
    [Migration("20260806134905_UserIdMustBeULONG")]
    partial class UserIdMustBeULONG
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("thefirey33_backend.Types.Database.QuestionDbType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasJsonPropertyName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attachment")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasJsonPropertyName("attachment");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasJsonPropertyName("author");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasJsonPropertyName("question");

                    b.Property<DateTime>("QuestionPostTime")
                        .HasColumnType("timestamp with time zone")
                        .HasJsonPropertyName("time");

                    b.Property<string>("Response")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasJsonPropertyName("author_id");

                    b.HasKey("Id");

                    b.ToTable("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
