events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        
        location / {
            root /usr/share/nginx/html;
            index index.html;
            add_header Cross-Origin-Embedder-Policy "credentialless";
            add_header Cross-Origin-Opener-Policy "same-origin";
            try_files $uri $uri/ /index.html;
        } 
    }
    
}